// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxnaoqpsmfqmoriqvipy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bmFvcXBzbWZxbW9yaXF2aXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODExNjgsImV4cCI6MjA2ODk1NzE2OH0.hKjc2wUvrEF_JYB-fh8LDM-0J9Y7MHwY2R43MRb7Gh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});